Algoritmo "Exercício 16"

Var
 n1,n2,n3,n4,n5,soma:real


Inicio
    escreval("Digite a n1:")
    leia(n1)
    escreval("Digite a n2:")
    leia(n2)
    escreval("Digite a n3:")
    leia(n3)
    escreval("Digite a n4:")
    leia(n4)
    escreval("Digite a n1:")
    leia(n1)
    escreval("Digite a n5:")
    leia(n5)



soma <- n1 + n2 + n3 + n4 + n5


    escreva("A soma de todos números é:",soma)

Fimalgoritmo