Algoritmo "Exercício 03"

// Solicite o nome e idade de 3 pessoas. ENQUANTO
Var
nome: caractere
idade: inteiro
contador: inteiro

Inicio
contador <- 1

para contador de 1 ate 3 faca
escreval("Digite seu nome ", contador, ": ")
leia(nome)

escreval("Digite sua idade ",contador, ": ")
leia(idade)

escreval("Nome da pessoa ", contador, ":", nome)
escreval("Idade da pessoa ",contador, ":", idade)
escreval("")


fimpara

Fimalgoritmo


