Algoritmo "Algoritmo"
//  
//  

Var
    a,b: inteiro
    t, valor, porcentagem: real

Inicio

    escreval("Digite dois valores")
    escreval("Primeiro valor:")
    leia(a)
    escreval("Segundo valor:")
    leia(b)

    t := a+b
    valor := t * 0.45

    escreval("A soma dos valores",a," e",b," é igual a",t)

    escreval("")

    escreval("E a porcentagem de 45% da soma desses numeros é:",valor)
    
  Fimalgoritmo