Algoritmo "Exercicio 01"
//Solicitar o nome e a idade de uma pessoa e informar
//ao usuário se ela já pode ou não tirar CNH//
Var
nome:caractere
idade:inteiro

Inicio
escreval("Digite seu nome:")
leia(nome)

escreval("Digite sua idade:")
leia(idade)

se idade >= "18" entao
escreval("Voce ja pode tirar CNH")

senao
escreval("Voce ainda nao pode tirar CNH")

fimse

Fimalgoritmo